openapi: 3.0.0
info:
  title: channel
  version: 1.0.0-dev
  description: Open API spec for Print Trail API
  contact:
    name: Hansen Salim
  x-logo:
    url: 'https://print-trail.github.io/api-spec/logo.png'
    backgroundColor: '#fafafa'
    altText: Print Trail Logo
servers:
  - url: 'https://pt-core.consilstaging.com/api'
    description: Staging
  - url: 'https://api.printtrail.com/api'
    description: Production
  - url: 'http://localhost:80/api'
    description: Local development 1
  - url: 'http://api.localhost:80'
    description: Local development 2
paths:
  '/v1/channels/{channelId}/orders/{orderUuid}':
    parameters:
      - schema:
          type: string
        name: orderUuid
        in: path
        required: true
      - $ref: '#/components/parameters/channelId'
    get:
      summary: Get order
      tags:
        - Order
        - All
      responses:
        '200':
          description: Order Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
              examples:
                example-order-1:
                  value:
                    data:
                      uuid: 7370c4d5-4711-4360-bb1d-bb442262f19d
                      purchaseOrder: DEPT/123/abc
                      orderNumber: 12345a
                      printTrailOrderNumber: ptbp-order-pt-00001234
                      status: draft
                      fulfillableStatus: draft
                      createdAt: '2021-02-23T15:54:53.000000Z'
                      cancelStatus: allowed
                      shippingDetails:
                        postalAddress:
                          companyName: Consilience
                          postalCode: NE26 2HU
                          address1: 305 Whitley Road
                          address2: North Tyneside
                          address3: ''
                          address4: ''
                          locality: ''
                          city: Whitley Bay
                          state:
                            name: Tyne & Wear
                            code: NY
                          country:
                            name: United Kingdom
                            code: GB
                        deliveryContact:
                          firstName: Jane
                          lastName: Doe
                          mobile: +44 7771 123456
                          phone: +1 987 1234567
                          email: jane.doe@example.com
                        note: Leave the item behind the plant pot.
                      fulfilments:
                        - uuid: 5ef3ad62-a74f-4ef5-85fe-925ab6f18df7
                          productionMethod: pod
                          supplierLocation:
                            code: uk-northwest
                            countryCode: GB
                          status: draft
                          orderLines:
                            - quantity: 23
                              lineNumber: ptbd-order-0001234/004
                              fulfilmentUuid: 67e8cbd0-282a-4e2a-a44b-9502d53c9d00
                              product:
                                name: My Happy Place Book
                                sku: BOOK/HB/abc-123
                                type: pod
                                description: string
                                additionalDetails:
                                  - key: number_of_pages
                                    value: '320'
                                podEnabled: false
                                warehouseEnabled: false
                                activeState: active
                                dimensions:
                                  weight:
                                    measurement: 23
                                    unit: kg
                                  length:
                                    measurement: 23
                                    unit: mm
                                  width:
                                    measurement: 23
                                    unit: mm
                                  depth:
                                    measurement: 23
                                    unit: mm
                                price:
                                  - net:
                                      currencyCode: GBP
                                      amountMinorUnits: 1299
                                uuid: 83b0e08f-aa07-4a5b-b74b-c578bfe89359
                              price:
                                itemNet:
                                  currencyCode: GBP
                                  amountMinorUnits: 1299
                      orderLines:
                        - quantity: 23
                          lineNumber: ptbd-order-0001234/004
                          fulfilmentUuid: 67e8cbd0-282a-4e2a-a44b-9502d53c9d00
                          product:
                            name: My Happy Place Book
                            sku: BOOK/HB/abc-123
                            type: pod
                            description: A big book of things.
                            additionalDetails:
                              - key: number_of_pages
                                value: '320'
                            podEnabled: false
                            warehouseEnabled: false
                            activeState: active
                            dimensions:
                              weight:
                                measurement: 23
                                unit: kg
                              length:
                                measurement: 23
                                unit: mm
                              width:
                                measurement: 23
                                unit: mm
                              depth:
                                measurement: 23
                                unit: mm
                            price:
                              - net:
                                  currencyCode: GBP
                                  amountMinorUnits: 1299
                            uuid: 83b0e08f-aa07-4a5b-b74b-c578bfe89359
                          price:
                            itemNet:
                              currencyCode: GBP
                              amountMinorUnits: 1299
                      errors:
                        - code: invalid-sku
                          message: The SKU is not recognised for any available product.
                          key: ptbd-order-1234-line-002
        '404':
          description: Order Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
      operationId: getOrder
      description: Retrieve the information of the order with the matching order UUID.
  '/v1/channels/{channelId}/orders':
    post:
      summary: Create new draft order
      operationId: createOrder
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
              examples:
                example-order-created:
                  value:
                    data:
                      uuid: 7370c4d5-4711-4360-bb1d-bb442262f19d
                      purchaseOrder: DEPT/123/abc
                      orderNumber: 12345a
                      printTrailOrderNumber: ptbp-order-pt-00001234
                      status: draft
                      fulfillableStatus: fulfillable
                      createdAt: '2021-02-23T15:54:53.000000Z'
                      cancelStatus: allowed
                      shippingDetails:
                        postalAddress:
                          companyName: Consilience
                          postalCode: NE26 2HU
                          address1: 305 Whitley Road
                          address2: North Tyneside
                          address3: ''
                          address4: ''
                          locality: ''
                          city: Whitley Bay
                          state:
                            name: Tyne & Wear
                            code: NY
                          country:
                            name: United Kingdom
                            code: GB
                        deliveryContact:
                          firstName: Fred
                          lastName: East
                          mobile: none
                          phone: none
                          email: fred.east@example.com
                        note: string
                      fulfilments:
                        - uuid: af6513a1-112b-4184-aeac-e3ab5c99cb38
                          productionMethod: warehouse
                          supplierLocation:
                            code: uk-northwest
                            countryCode: GB
                          status: processing
                          orderLines:
                            - quantity: 23
                              lineNumber: ptbd-order-0001234/004
                              fulfilmentUuid: 67e8cbd0-282a-4e2a-a44b-9502d53c9d00
                              product:
                                name: My Happy Place Book
                                sku: BOOK/HB/abc-123
                                type: pod
                                description: string
                                additionalDetails:
                                  - key: number_of_pages
                                    value: '320'
                                podEnabled: true
                                warehouseEnabled: true
                                activeState: active
                                dimensions:
                                  weight:
                                    measurement: 23
                                    unit: kg
                                  length:
                                    measurement: 23
                                    unit: mm
                                  width:
                                    measurement: 23
                                    unit: mm
                                  depth:
                                    measurement: 23
                                    unit: mm
                                price:
                                  - currencyCode: GBP
                                    amountMinorUnits: 1299
                      errors:
                        - code: invalid-sku
                          message: The SKU is not recognised for any available product.
                          key: ptbd-order-1234-line-002
        '400':
          description: Bad Request
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
              examples:
                example-validation-errors:
                  value:
                    type: 'about:blank'
                    status: 422
                    title: Validation errors
                    violations:
                      - property: shippingDetails.postalAddress.country.code
                        message: The shipping details.postal address.country.code may not be greater than 3 characters.
                      - property: shippingDetails.deliveryContact.email
                        message: The shipping details.delivery contact.email must be a valid email address.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
            examples:
              example-1:
                value:
                  purchaseOrder: DEPT/123/abc
                  orderNumber: 12345a
                  status: draft
                  shippingDetails:
                    postalAddress:
                      companyName: Consilience
                      postalCode: NE26 2HU
                      address1: 305 Whitley Road
                      address2: North Tyneside
                      address3: ''
                      address4: ''
                      locality: ''
                      city: Whitley Bay
                      state:
                        name: Tyne & Wear
                        code: NY
                      country:
                        name: United Kingdom
                        code: GB
                    deliveryContact:
                      firstName: Jane
                      lastName: Doe
                      mobile: ''
                      phone: ''
                      email: jane.doe@example.com
                    note: Leave the item behind the plant pot.
        description: Post the necessary fields for the API to create a new order.
      description: |-
        Create a new draft order or replace an existing draft order.

        If the orderNumber supplied is for an order that already exists, then it replaces the existing order so long as it is in a fully cancellable state.
      tags:
        - Order
        - All
      parameters: []
    parameters:
      - $ref: '#/components/parameters/channelId'
    get:
      summary: Search Orders
      operationId: searchOrders
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderSearchResponse'
        '404':
          description: Not Found
      parameters:
        - schema:
            type: string
            format: uuid
            example: 5656d05e-1398-49f4-95fd-8b50c1a8e196
          in: query
          name: uuid
          description: Match a specific UUID or comma-separated list of UUIDs
          style: form
          allowEmptyValue: true
        - schema:
            type: string
          in: query
          name: order-number
          description: Match the e-commerce site order number
        - schema:
            type: string
          in: query
          name: purchase-order
          description: Match the e-commerce site order number
        - schema:
            type: integer
            minimum: 1
            format: int32
            example: 2
          in: query
          name: page
          description: The page number of the result set
      description: Select a collection of matching orders.
      tags:
        - Order
        - All
  '/v1/channels/{channelId}/team':
    get:
      summary: Get team info
      tags:
        - Team
        - All
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeamResponse'
              examples: {}
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
      operationId: getTeam
      description: Get Team details.
    parameters:
      - $ref: '#/components/parameters/channelId'
  '/v1/channels/{channelId}':
    parameters:
      - $ref: '#/components/parameters/channelId'
    get:
      summary: Get channel info
      tags:
        - Channel
        - All
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChannelResponse'
              examples:
                example-1:
                  value:
                    data:
                      id: webt-cha
                      name: Web Team Channels
                      state: active
                      mode: live
                      lastSyncedAt: '2019-08-24T14:15:22Z'
                      webhookUrl: 'https://wxample.com/'
                      code: cha
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
      operationId: getChannel
      description: Get channel detail.
  '/v1/channels/{channelId}/products':
    parameters:
      - $ref: '#/components/parameters/channelId'
    get:
      summary: Search All Products
      tags:
        - Product
        - All
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductSearchResponse'
              examples:
                example-1:
                  value:
                    data:
                      - name: My Happy Place Book
                        sku: BOOK/HB/abc-123
                        type: warehouse
                        description: string
                        additionalDetails:
                          - key: string
                            value: string
                        podEnabled: true
                        warehouseEnabled: true
                        activeState: active
                        dimensions:
                          weight:
                            measurement: 23
                            unit: kg
                          length:
                            measurement: 23
                            unit: mm
                          width:
                            measurement: 23
                            unit: mm
                          depth:
                            measurement: 23
                            unit: mm
                        price:
                          - currencyCode: GBP
                            amountMinorUnits: 499
                    meta:
                      current_page: 0
                      from: 0
                      path: string
                      per_page: 0
                      to: 0
                      total: 0
                    links:
                      first: 'http://178.128.35.155/api/fulfilments?page=1'
                      last: 'http://178.128.35.155/api/fulfilments?page=2'
                      prev: 'http://example.com'
                      next: 'http://example.com'
      operationId: searchProducts
      description: 'Retrieve all products for a channel, according to the filter.'
      parameters:
        - schema:
            type: integer
            minimum: 1
            example: 2
            default: 1
          in: query
          name: page
          description: The page number to start on.
        - schema:
            type: string
            format: uuid
            example: 3272cb75-4260-49d5-b28f-6e5cc038d766
          in: query
          name: uuid
          description: Match a specific product UUID
        - schema:
            type: string
            example: My % Book
          in: query
          name: name
          description: 'Match a product name, with wildcard support'
        - schema:
            type: string
            example: BOOK/HB/abc-%
          in: query
          name: sku
          description: 'Match a product SKU, with wildcard support'
  '/v1/channels/{channelId}/orders/{orderUuid}/confirm':
    parameters:
      - $ref: '#/components/parameters/channelId'
      - schema:
          type: string
        name: orderUuid
        in: path
        required: true
    put:
      summary: Confirm Order
      operationId: confirmOrder
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '202':
          description: Accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
      description: Confirm an existing draft order to be processed.
      tags:
        - Order
        - All
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderConfirmDetails'
  '/v1/channels/{channelId}/orders/{orderUuid}/cancel':
    parameters:
      - $ref: '#/components/parameters/channelId'
      - schema:
          type: string
        name: orderUuid
        in: path
        required: true
    put:
      summary: ''
      operationId: cancelOrder
      responses:
        '200':
          description: OK
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
      tags:
        - Order
        - All
      description: |-
        Cancel a draft order. Removes its draft order lines and fulfilments, releasing any reserved stock.

        An order may be too late to cancel if it has already moved on to the fulfilment stage. A request can still be submitted to cancel it, but the result is no guarantee, and some charges may still apply.
      parameters: []
  '/v1/channels/{channelId}/products/{productUuid}':
    parameters:
      - $ref: '#/components/parameters/channelId'
      - schema:
          type: string
          format: uuid
          example: 0a1b52cc-b16c-4f40-8522-68186018a8fc
        name: productUuid
        in: path
        required: true
        description: Selects the product
    get:
      summary: Your GET endpoint
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductResponse'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Problem'
      operationId: getProduct
      description: Return a single product by UUID.
components:
  schemas:
    Order:
      type: object
      description: ''
      x-examples: {}
      title: ''
      properties:
        uuid:
          type: string
          minLength: 1
          format: uuid
          description: 'Order identifier, set by Print Trail when a draft order is created.'
          example: 7370c4d5-4711-4360-bb1d-bb442262f19d
        purchaseOrder:
          type: string
          description: |-
            The purchase order number to be assigned to this order.

            Note: may not be supported from the start.
          example: DEPT/123/abc
          maxLength: 50
        orderNumber:
          type: string
          minLength: 1
          description: |
            Order number from the channel, i.e. the shop. Every order placed on a channel must have a unique order number.
          example: 12345a
        printTrailOrderNumber:
          type: string
          minLength: 1
          description: Order number generated by Print Trail for internal use.
          example: ptbp-order-pt-00001234
          readOnly: true
        status:
          type: string
          minLength: 1
          description: |-
            Current order status.

            Details TBC.
          enum:
            - draft
            - queued
            - holding
            - processing
            - complete
            - cancelled
            - back-order
            - returned
            - invalid
            - error
            - partial
            - failed
          example: draft
          readOnly: true
        fulfillableStatus:
          type: string
          minLength: 1
          enum:
            - draft
            - fulfillable
            - partially_fulfillable
            - not_fulfillable
            - error
          description: |-
            Indicates whether this order can be fulfilled by Print Trail, either fully, partially, or not at all. Only fulfillable orders can be confirmed - no partial orders will be processed.

            Values are:

            * `draft` - still being processed.
            * `fulfillable` - the complete order is fulfillable and draft fulfilments have been created.
            * `partially_fulfillable` - some of the order lines can be fulfilled, but not all. Draft fulfilments have been created for those that can, but the order cannot  be progressed.
            * `not_fulfillable` - no order line can be fulfilled for this order.
            * `error` - an error was encountered while trying to calculate the fulfilments. The `errors` array will provide further details.
          example: fulfillable
          readOnly: true
        createdAt:
          type: string
          minLength: 1
          format: date-time
          description: Timestamp for when this order was first created.
          example: '2021-02-23T15:54:53.000000Z'
          readOnly: true
        cancelStatus:
          type: string
          description: |-
            Indicate whether Print Trail would still accept a cancellation request for this order. Note: even when an order is "cancellable" the cancellation request may still fail.

            FIXME: these need some more thought to distinguish between "allowed" vs "allowed but no guarantees" vs "too late".
          enum:
            - allowed
            - not-allowed
            - cancelling
            - cancelled
          readOnly: true
        shippingDetails:
          $ref: '#/components/schemas/OrderShippingDetails'
        fulfilments:
          type: array
          uniqueItems: true
          minItems: 1
          description: Details of the fulfilments the order is going to be split into.
          items:
            $ref: '#/components/schemas/Fulfilment'
          readOnly: true
        orderLines:
          type: array
          uniqueItems: true
          minItems: 1
          description: The original order lines supplied by the channel shop.
          items:
            $ref: '#/components/schemas/OrderLine'
        errors:
          type: array
          description: Errors related to this order
          items:
            $ref: '#/components/schemas/ErrorDetail'
          readOnly: true
    Team:
      type: object
      description: Summary details about the team that owns and manages the channel.
      x-examples: {}
      properties:
        name:
          type: string
          minLength: 1
          description: The common name of the team or organisation.
          example: Jolly Good Book Publishing
        returnsPolicyUrl:
          type: string
          minLength: 1
          format: uri
          description: URL to the page providing details about the team's returns policy.
          example: 'https://example.com/returns-policy'
        code:
          type: string
          minLength: 4
          maxLength: 4
          description: |-
            The short code for the team.

            This code may be seen used as prefixes to a number of references across the API.
          example: ptbp
      required:
        - name
        - code
      readOnly: true
      title: ''
    Channel:
      type: object
      description: Overall details and metadata for a channel.
      title: ''
      properties:
        id:
          type: string
          minLength: 8
          maxLength: 8
          example: webt-cha
          description: The channel ID is globally unique. It will comprise of the team code concatenated with the channel code.
        name:
          type: string
          minLength: 1
          description: The name given to the channel by the team.
        state:
          type: string
          enum:
            - active
            - inactive
          description: |-
            The state the channel is in:

            * active - the channel can be used to place and check orders.
            * inactive - the channel cannot be used to place orders.

            Note: additional states may be introduced to indicate varying levels of operation.
        mode:
          type: string
          minLength: 1
          enum:
            - live
            - test
          description: |
            The mode the channel is operating in.

            * live - orders will be attempted to be processed and dispatched to customers.
            * test - orders will not result in fulfilments being dispatched to customers.
        lastSyncedAt:
          type: string
          format: date-time
          description: TBC
          example: '2021-04-21T12:13:14+00:00'
        webhookUrl:
          type: string
          minLength: 1
          description: 'The URL that notifications will be sent to, for processing by the shop on the channel. Notifications include order acceptance, shipping, cancellation.'
        code:
          type: string
          minLength: 3
          maxLength: 3
          example: cha
          description: The channel code is unique within a team.
        team:
          $ref: '#/components/schemas/Team'
      required:
        - id
        - name
        - state
        - mode
        - webhookUrl
        - code
      readOnly: true
    Product:
      type: object
      description: A product fulfilled by Print Trail.
      properties:
        name:
          type: string
          minLength: 1
          example: My Happy Place Book
          readOnly: true
        sku:
          type: string
          minLength: 1
          description: The public/shop product SKU as registered in Print Trail.
          example: BOOK/HB/abc-123
        type:
          type: string
          minLength: 1
          example: pod
          enum:
            - pod
            - warehouse
          readOnly: true
        description:
          type: string
          minLength: 1
          readOnly: true
        additionalDetails:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            type: object
            properties:
              key:
                type: string
                minLength: 1
                example: number_of_pages
              value:
                type: string
                minLength: 1
                example: '320'
            required:
              - key
              - value
          readOnly: true
        podEnabled:
          type: boolean
          default: false
          readOnly: true
        warehouseEnabled:
          type: boolean
          default: false
          readOnly: true
        activeState:
          type: string
          example: active
          enum:
            - active
            - inactive
          default: active
          description: inactive products cannot be ordered
          readOnly: true
        dimensions:
          $ref: '#/components/schemas/Dimensions'
        price:
          type: array
          uniqueItems: true
          minItems: 1
          items:
            $ref: '#/components/schemas/ProductPrice'
          readOnly: true
        uuid:
          type: string
          format: uuid
          description: Can be used as an alternative to SKU when writing order lines.
          example: 83b0e08f-aa07-4a5b-b74b-c578bfe89359
      required:
        - name
        - type
        - description
        - additionalDetails
        - activeState
    Fulfilment:
      type: object
      description: |-
        A collection of order lines that will be fulfilled by a single production location. Order lines from a single order that can be fulfilled by Print Trail will be split into one or more fulfilments.

        Each item is for one original order line.

        Note the use of British English spelling of 'fulfilment'.
      properties:
        uuid:
          type: string
          minLength: 1
          description: The globally unique ID of the fulfilment.
          example: e4a5968e-3756-460e-85ab-0a8de249dac0
        productionMethod:
          type: string
          minLength: 1
          enum:
            - pod
            - warehouse
          example: pod
        supplierLocation:
          $ref: '#/components/schemas/SupplierLocation'
        status:
          type: string
          minLength: 1
          enum:
            - draft
            - processing
            - dispatched
            - cancelled
            - returned
            - invalid
            - failed
            - error
            - holding
            - back-order
          example: draft
        orderLines:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/OrderLine'
        availableShippingMethods:
          type: array
          minItems: 0
          items:
            type: string
            pattern: '^[a-z0-9-]+$'
            minLength: 1
            maxLength: 60
          readOnly: true
          example:
            - standard
            - express
        requestedShippingMethod:
          type: string
          pattern: '^[a-z0-9-]+$'
          minLength: 1
          maxLength: 60
      required:
        - uuid
        - productionMethod
        - supplierLocation
        - status
        - orderLines
        - availableShippingMethods
      readOnly: true
    PostalAddress:
      type: object
      title: PostalAddress
      description: A postal address for a shipment. This model is used to both set and inspect the postal address for a fulfilment.
      properties:
        companyName:
          type: string
          minLength: 1
          example: Consilience
        postalCode:
          type: string
          minLength: 1
          example: NE26 2HU
        address1:
          type: string
          minLength: 1
          description: |
            single line string for the address. Multi line address should be separated to address2, and so on.
          example: 305 Whitley Road
        address2:
          type: string
          description: Second line of the address
          example: North Tyneside
        address3:
          type: string
        address4:
          type: string
        locality:
          type: string
          description: Used in some addresses to sub-divide a state or province.
        city:
          type: string
          minLength: 1
          example: Whitley Bay
        state:
          $ref: '#/components/schemas/State'
        country:
          $ref: '#/components/schemas/Country'
      required:
        - address1
        - country
    Contact:
      title: Contact
      type: object
      description: Contact details. Common details apart from an address.
      properties:
        firstName:
          type: string
          example: Jane
          maxLength: 100
        lastName:
          type: string
          maxLength: 100
          example: Doe
        mobile:
          type: string
          maxLength: 50
          example: +44 7771 123456
        phone:
          type: string
          maxLength: 50
          example: +1 987 1234567
        email:
          type: string
          format: email
          maxLength: 100
          example: jane.doe@example.com
      required:
        - firstName
    OrderResponse:
      title: OrderResponse
      type: object
      description: A single order wrapped as an API response.
      properties:
        data:
          $ref: '#/components/schemas/Order'
    ProductSearchResponse:
      title: ProductsResponse
      type: object
      description: Mutiple products wrapped in a response API with pager details.
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        meta:
          $ref: '#/components/schemas/PagerMeta'
        links:
          $ref: '#/components/schemas/PagerLinks'
    PagerLinks:
      title: PagerLinks
      type: object
      description: Meta pagination links within
      properties:
        first:
          type: string
          example: 'http://178.128.35.155/api/fulfilments?page=1'
          format: uri
        last:
          type: string
          example: 'http://178.128.35.155/api/fulfilments?page=2'
          format: uri
        prev:
          type: string
          format: uri
        next:
          type: string
          format: uri
      required:
        - first
        - last
    PagerMeta:
      type: object
      title: PagerMeta
      properties:
        current_page:
          type: integer
          example: 2
          description: The number of the current page returned by this query and selection.
        from:
          type: integer
          description: The first record number on the page.
          example: 1
        path:
          type: string
          description: The root path to this index page.
        per_page:
          type: integer
          example: 50
          description: The number of records each page can contain.
        to:
          type: integer
          description: The last record number on the page.
          example: 50
        total:
          type: integer
          description: The total number of records this search matches.
          example: 477
        last_page:
          type: integer
          description: The last page number for this query.
          example: 7
      readOnly: true
    OrderLine:
      title: OrderLine
      type: object
      description: The details of an order line provided by the shop.
      properties:
        quantity:
          type: number
          minimum: 1
          example: 23
          description: |-
            Number of these items in this line.

            Integer values only accepted at this time.
        lineNumber:
          type: string
          example: ptbd-order-0001234/004
          description: |-
            The persistent identifier for this order line, unique within the order, as defined by the shop.

            This allows order lines within the e-commerce application to be tied to fulfilments generated by Print Trail.
        fulfilmentUuid:
          type: string
          format: uuid
          description: The filfilment UUID if the orderline is fulfilled (this includes draft fulfilments).
          readOnly: true
        product:
          $ref: '#/components/schemas/Product'
        price:
          $ref: '#/components/schemas/OrderLinePrice'
      required:
        - quantity
        - lineNumber
    ErrorDetail:
      type: object
      title: ErrorDetail
      description: |-
        Details for a single error.

        Lists of errors may be generated when drafting an order, or when servicing a fulfilment.
      properties:
        code:
          type: string
          description: |-
            Error code to indicate the category of error.

            TBC details and list. The error codes will not be enumerated in the API description, as new codes may be created as new error conditions are discovered.
          pattern: '[a-z][a-z0-9-]+'
          example: invalid-sku
          default: general
          readOnly: true
        message:
          type: string
          description: 'Human-readable error message, suitable for presenting to an end user in context.'
          example: The SKU is not recognised for any available product.
          readOnly: true
        key:
          type: string
          description: |-
            The key property that this error is about.

            If no key is provided, then the error is about the object it is on. That may be an order or a fulfilment.

            If a key is provided, then it narrows down the error to a child record, an order line or a fulfilment line (to be confirmed).
          example: ptbd-order-1234-line-002
          readOnly: true
      required:
        - code
        - message
      readOnly: true
    OrderShippingDetails:
      title: OrderShippingDetails
      type: object
      description: Shipping details for an order.
      x-internal: false
      properties:
        postalAddress:
          $ref: '#/components/schemas/PostalAddress'
        deliveryContact:
          $ref: '#/components/schemas/Contact'
        note:
          type: string
          description: |-
            Notes to add to this shipment.

            TBC: how this field will be used, and any limitations.
          example: Leave the item behind the plant pot.
          maxLength: 200
    ChannelResponse:
      title: ChannelResponse
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Channel'
      description: A single channel detail.
    TeamResponse:
      title: TeamResponse
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Team'
      description: A single team wrapped in an API response.
    MeasurementMass:
      title: MeasurementMass
      type: object
      description: A single mass measurement of a given unit.
      properties:
        measurement:
          type: number
          example: 23
        unit:
          type: string
          enum:
            - kg
            - g
            - lb
            - lbs
          example: kg
      required:
        - measurement
        - unit
    MeasurementLength:
      title: MeasurementLength
      type: object
      description: A single length measurement of a given unit.
      properties:
        measurement:
          type: number
          example: 23
        unit:
          type: string
          enum:
            - mm
            - cm
            - in
            - m
          example: mm
      required:
        - measurement
        - unit
    Dimensions:
      type: object
      title: Dimensions
      description: All dimensions of a single object.
      properties:
        weight:
          $ref: '#/components/schemas/MeasurementMass'
        length:
          $ref: '#/components/schemas/MeasurementLength'
        width:
          $ref: '#/components/schemas/MeasurementLength'
        depth:
          $ref: '#/components/schemas/MeasurementLength'
      readOnly: true
    MoneyAmount:
      title: MoneyAmount
      type: object
      description: A monetary amount with a value and a currency.
      properties:
        currencyCode:
          type: string
          description: ISO three-character currency code.
          example: GBP
          minLength: 3
          maxLength: 3
        amountMinorUnits:
          type: integer
          example: 1299
          description: |-
            The amount in minor units.

            Example: 1299 for $12.99
      required:
        - currencyCode
        - amountMinorUnits
    Country:
      title: Country
      type: object
      properties:
        name:
          type: string
          minLength: 1
          example: United Kingdom
        code:
          type: string
          minLength: 1
          description: |-
            ISO 3166-1 alpha-2 country code.

            When creating an order, the ISO 3166-1 alpha-3 code can also be supplied, but Print Trail will always return the alpha-2 code.
          example: GB
    State:
      title: State
      type: object
      properties:
        name:
          type: string
          minLength: 1
          example: Tyne & Wear
          description: The full name of the state or province.
        code:
          type: string
          example: NY
          description: 'The abbreviation or code for the state or province, where it applies (and is commonly used in addressing).'
    SupplierLocation:
      title: SupplierLocation
      type: object
      description: 'Details of the supplier location, where fulfilments will be shipped from.'
      properties:
        code:
          type: string
          minLength: 1
          example: uk-northwest
          readOnly: true
        countryCode:
          type: string
          minLength: 1
          example: GB
          description: ISO 3166 2-alpha code
      required:
        - code
    OrderSearchResponse:
      title: OrderSearchResponse
      type: object
      description: The results of selecting for a page of orders.
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/Order'
        meta:
          $ref: '#/components/schemas/PagerMeta'
        links:
          $ref: '#/components/schemas/PagerLinks'
    ProductResponse:
      title: ProductResponse
      type: object
      properties:
        data:
          $ref: '#/components/schemas/Product'
      description: The payload rersponse for a single product.
    Problem:
      type: object
      description: |-
        RFC7807 problem schema.

        See https://tools.ietf.org/html/rfc7807
      properties:
        type:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the problem type.  When dereferenced,
            it SHOULD provide human-readable documentation for the problem type
            (e.g., using HTML).
          default: 'about:blank'
          example: 'https://printtrail.com/problem/constraint-violation'
        title:
          type: string
          description: |
            A short, summary of the problem type. Written in English and readable
            for engineers (usually not suited for non-technical stakeholders and
            not localized); example: Service Unavailable
          example: Not found
        status:
          type: integer
          format: int32
          description: |
            The HTTP status code generated by the origin server for this occurrence
            of the problem.
          minimum: 100
          maximum: 600
          exclusiveMaximum: true
          example: 503
        detail:
          type: string
          description: |
            A human-readable explanation specific to this occurrence of the
            problem.
          example: This order is not in a state (error) that can be confirmed
        instance:
          type: string
          format: uri
          description: |
            An absolute URI that identifies the specific occurrence of the problem.
            It may or may not yield further information if dereferenced.

            Not yet used in this API.
        violations:
          type: array
          description: List of validation errors.
          items:
            $ref: '#/components/schemas/ProblemViolation'
          readOnly: true
      readOnly: true
    ProductPrice:
      title: ProductPrice
      type: object
      description: |-
        All price details for a product, as known by Print Trail.

        Further details of this TBC.
      properties:
        net:
          $ref: '#/components/schemas/MoneyAmount'
    OrderLinePrice:
      title: OrderLinePrice
      type: object
      properties:
        itemNet:
          $ref: '#/components/schemas/MoneyAmount'
      description: |-
        The price components for an order line, as declared by the shop. These may differ from the product price (where that is even known) since they relate to what was charged for this order, including current discounts and specific taxes.

        Full details for this object TBC.
    ProblemViolation:
      type: object
      title: ProblemViolation
      description: A validation error.
      properties:
        property:
          type: string
          example: shippingDetails.postalAddress
          readOnly: true
        message:
          type: string
          description: Human readable message.
          example: The shipping details.postal address.country.code may not be greater than 3 characters.
          readOnly: true
      readOnly: true
    ConfirmShippingDetails:
      type: object
      title: ConfirmShippingDetails
      properties:
        fulfilmentUuid:
          type: string
          format: uuid
          description: The fulfilment UUID.
          example: f0182a12-b5a8-4997-bb33-773932afc53d
        shippingMethod:
          type: string
          pattern: '^[a-z0-9-]+$'
          minLength: 1
          maxLength: 60
          description: The shipping method to use for this fulfilment.
          example: express
      required:
        - fulfilmentUuid
        - shippingMethod
      writeOnly: true
    OrderConfirmDetails:
      type: object
      title: OrderConfirmDetails
      description: Additional details to add during the draft order confirm request.
      properties:
        fulfilmentShippingMethods:
          type: array
          minItems: 0
          description: Allows each filfilment to get its own desired shipping method.
          items:
            $ref: '#/components/schemas/ConfirmShippingDetails'
        defaultShippingMethod:
          type: string
          description: The shipping method to use for any fulfilment that does not have its own specific shipping method.
          pattern: '^[a-z0-9-]+$'
          maxLength: 60
          minLength: 1
          example: standard
          writeOnly: true
      writeOnly: true
      x-examples:
        example-1:
          fulfilmentShippingMethods:
            - fulfilmentUuid: f0182a12-b5a8-4997-bb33-773932afc53d
              shippingMethod: express
  securitySchemes:
    ChannelApiKey:
      type: http
      scheme: bearer
  responses: {}
  parameters:
    channelId:
      name: channelId
      in: path
      required: true
      schema:
        type: string
        pattern: '[a-z0-9]-[a-z0-9]'
        example: acme-bks
        minLength: 8
        maxLength: 20
      description: The channel id connecting the shop to the Print Trail team
tags:
  - name: All
  - name: Channel
  - name: Order
  - name: Product
  - name: Team
security:
  - ChannelApiKey: []
